version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: 6ix_wallet_mysql
    environment:
      MYSQL_ROOT_PASSWORD: r00tpassword
      MYSQL_DATABASE: 6ixwallet
      MYSQL_USER: 6ixthedev
      MYSQL_PASSWORD: p@ssw0rd
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db_data:
